INSERT INTO quizzes (owner_id, public, title, subject, image_url, url) VALUES (5, TRUE, 'Mega Fun Quiz Time!', 'miscellaneous facts', 'https://images.pexels.com/photos/39561/solar-flare-sun-eruption-energy-39561.jpeg', 'newquiz1');
INSERT INTO quizzes (owner_id, public, title, subject, image_url, url) VALUES (4, FALSE, 'Algorithm Test!', 'Binary Search', 'https://images.pexels.com/photos/355935/pexels-photo-355935.jpeg?auto=compress&cs=tinysrgb&w=400', 'newquiz2');
INSERT INTO quizzes (owner_id, public, title, subject, image_url, url) VALUES (5, TRUE, 'Music Time', 'Tone Rows', 'https://images.pexels.com/photos/11308623/pexels-photo-11308623.jpeg?auto=compress&cs=tinysrgb&w=400', 'newquiz3');
INSERT INTO quizzes (owner_id, public, title, subject, image_url, url) VALUES (2, TRUE, 'Fast Quiz', 'Death Metal', 'https://images.pexels.com/photos/11591876/pexels-photo-11591876.jpeg?auto=compress&cs=tinysrgb&w=400', 'newquiz4');
INSERT INTO quizzes (owner_id, public, title, subject, image_url, url) VALUES (3, FALSE, 'Pop Quiz', 'Greatest Hits of the 20s', 'https://images.pexels.com/photos/1983037/pexels-photo-1983037.jpeg?auto=compress&cs=tinysrgb&w=400', 'newquiz5');
INSERT INTO quizzes (owner_id, public, title, subject, image_url, url) VALUES (1, FALSE, 'Great Work Nicholas.', 'you rock', 'https://images.pexels.com/photos/11174764/pexels-photo-11174764.jpeg?auto=compress&cs=tinysrgb&w=400', 'newquiz6');
INSERT INTO quizzes (owner_id, public, title, subject, image_url, url) VALUES (2, TRUE, 'In The Studio', 'Lengendary Recording Artits', 'https://images.pexels.com/photos/352505/pexels-photo-352505.jpeg?auto=compress&cs=tinysrgb&w=400', 'newquiz4');
INSERT INTO quizzes (owner_id, public, title, subject, image_url, url) VALUES (3, FALSE, 'Let Think for a Minute', 'Arithmetic and Algebra', 'https://images.pexels.com/photos/45975/rose-window-strasbourg-cathedral-strasbourg-france-45975.jpeg?auto=compress&cs=tinysrgb&w=300', 'newquiz5');
INSERT INTO quizzes (owner_id, public, title, subject, image_url, url) VALUES (1, FALSE, 'Technology at Home', 'a quiz on the advancement of domestic tech', 'https://images.pexels.com/photos/14063089/pexels-photo-14063089.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'newquiz6');
